version: "3"

networks:
  laravel:

services:
  # laravel-mysql:
  #   image: mysql:5.7.22
  #   container_name: laravel-mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3333:3306"
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - laravel
  laravel-nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8999:80"
    volumes:
      - ./src:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-php
      # - laravel-mysql
    networks:
      - laravel
  laravel-php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    container_name: laravel-php
    volumes: 
      - ./src:/var/www
    ports:
      - "9999:9000"
    networks:
      - laravel